version: '3.9'

services:
  mongo_db:
    container_name: mongo-db-container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  api:
    container_name: node-docker
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}


